name: Build Matlab toolbox installer
on:
  - push
  - workflow_dispatch
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build toolbox installer
        run: |
          make -C CI/scripts/ build
